{
  "idMapa": "mapa1",
  "nombreVisible": "Valle Verde - Reino Central",
  "mundoComienzo": "exterior",
  "spawnComienzo": "comienzo",
  "submundos": [
    {
      "id": "exterior",
      "archivo": "submundos/escenario1.wld",
      "tipoAmbiente": "EXTERIOR",
      "modoCarga": "PESADO"
    },
    {
      "id": "interior_casa1",
      "archivo": "submundos/interior_casa1.wld",
      "tipoAmbiente": "INTERIOR",
      "modoCarga": "LIGERO"
    },
    {
      "id": "cueva_1",
      "archivo": "submundos/cueva_1.wld",
      "tipoAmbiente": "CUEVA",
      "modoCarga": "LIGERO"
    },
    {
      "id": "ext_desierto",
      "archivo": "submundos/ext_desierto.wld",
      "tipoAmbiente": "EXTERIOR",
      "modoCarga": "PESADO"
    },
    {
      "id": "ext_nieve",
      "archivo": "submundos/ext_nieve.wld",
      "tipoAmbiente": "EXTERIOR",
      "modoCarga": "PESADO"
    }
  ]
}